# Generated by Django 2.1.3 on 2020-04-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_heading', models.CharField(max_length=250)),
                ('article_body', models.TextField()),
            ],
        ),
    ]
