# Generated by Django 2.1.3 on 2020-04-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_monitoring', '0003_gpustatusinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpustatusinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
