# Generated by Django 2.1.3 on 2020-04-12 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_monitoring', '0004_auto_20200412_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GpuStatusInfo',
        ),
        migrations.AddField(
            model_name='gpustatus',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gpustatus',
            name='index_gpu',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='gpustatus',
            name='label_gpu',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='gpustatus',
            name='server_group',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='gpustatus',
            name='server_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='gpustatus',
            name='util_gpu',
            field=models.IntegerField(default=0),
        ),
    ]
